# Generated by Django 5.1.6 on 2025-03-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_expense",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="merchant_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
